<?php

namespace Kiosk\UserBundle\Repository;

/**
 * ZoneAdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneAdresseRepository extends \Doctrine\ORM\EntityRepository
{
}
